### ISSUE TITLE
System (stl) headers are missed after updating to 1.4.0

### ISSUE THREAD

**Issue by sialiuk** [microsoft/vscode-cmake-tools#1257]
It looks like after updating to version 1.4.0 extension provides the wrong environment to cmake (Include Directories,), or something like that. 

- Operating System: Windows 10 x64
- CMake Version: 3.16.3
- VSCode Version: 1.45.1
- CMake Tools Extension Version: 1.4.0
- Compiler/Toolchain: MSVC 2019 x64
- Cmake generator: Ninja

I get compiler errors:
fatal error C1083: Cannot open include file: 'memory': No such file or directory
fatal error C1083: Cannot open include file: 'string': No such file or directory
.... and other system headers

The message just after Cmake: Configure command: 
![image](https://user-images.githubusercontent.com/1897738/82558900-5bb19680-9b77-11ea-9e67-abae561352d7.png)

Downgrading to 1.3.1 fixes the problem.

**Comment by sialiuk** [comment]
Looks like related to the issue https://github.com/microsoft/vscode-cmake-tools/issues/1243

**Comment by andreeis** [comment]
I am able to configure fine and the headers are found on my system for the kit and generator you mention (and for any other combinations). First, delete your build folder and try again. We have another bug that we're going to look at later regarding more robust cache and settings updates.

**Comment by sialiuk** [comment]
Thank you, deleting build folder(with resetting build kits) has helped!
I guess it is a problem updating from 1.3.1 to 1.4.0. 
Most probably 1.4.0 has some new build environment settings that are missed in 1.3.1 and after updating initializes them incorrectly.

**Comment by andreeis** [comment]
What do you mean resetting build kits? The kits should have been re-scanned automatically. You had to re-select the used kit?

**Comment by andreeis** [comment]
@sialiuk, I understand now how resetting the kit was needed as a step for getting unblocked. 
What would help, if you have a chance, is reproduce again the migration from 1.3.1 to 1.4.0 problem on your side and share with us the contents of your user kits json file. Besides other issues at play here (which we're working on for 1.4.1), there might be a problem with the silent rescan for kits we implemented in 1.4.0 in the hopes to automatically solve the breaking change in kits definition. You can help us confirm this theory. 
If you manage to do this (if it's not handy to reproduce again don't worry), share also a 'debug' log (cmake.loggingLevel=debug in settings) of the first time you load your project in VSCode after updating to 1.4.0. If you happen to not configure on open, share a log of the first configure you do post migration.

**Comment by andreeis** [comment]
This should be fixed in CMake Tools 1.4.1 which was published today.
Let us know if you encounter any issues with this release.
