### ISSUE TITLE
Can't start a second build (using Ninja)

### ISSUE THREAD

**Issue by josesimoes** [microsoft/vscode-cmake-tools#450]
### Brief Issue Summary
I can't start a second build because nothing happens. The output window remains with the information from the previous one. Only restarting VS Code resolves the situation.

I'm using Ninja for building. 
I have a GCC kit defined.

The CMakes that build the project have NOT changed and it works with CMake tools 0.10.4.

The output window show the build steps

### CMake Tools Log

[variant] Loaded new set of variants
[kit] Successfully loaded 14 kits from C:\Users\--------\AppData\Roaming\CMakeTools\cmake-kits.json
[kit] Successfully loaded 1 kits from e:\GitHub\nf-interpreter\.vscode\cmake-kits.json

After hitting F7

```
[cmake] Wire Protocol does NOT implement CRC32
[cmake] Support for networking IS NOT enabled
[cmake] RTOS is: ChibiOS (source from: E:/GitHub/ChibiOS)
...
[cmake] Configuring done
[cmake] Generating done
[build] Starting build
[proc] Executing command: E:\CMake\bin\cmake.EXE --build e:/github/nf-interpreter/build --config Debug --target all -- -j 10
[build] [1/379] Building C object targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/CMakeFiles/nanoBooter.elf.dir/__/__/__/__/ChibiOS_Source/os/hal/src/hal_dac.c.obj
...
[build] FAILED: targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/CMakeFiles/nanoCLR.elf.dir/nanoCLR/nanoHAL.cpp.obj 
[build] E:\GNU_Tools_ARM_Embedded ()...)
[build]                  from ../targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/nanoHAL.cpp:6:
```

The usual message of build failed message 1 is not there anymore.

Looks like if the tool isn't able to output whatever is coming from Ninja and gets stuck.

When hitting F7 again, it looks like the build starts. I can see a couple of lines and the CPU is high for a few seconds. But it never outputs anything that makes sense.

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.11.0
- **VSCode Version**: 1.23.1
- **CMake Tools Extension Version**: 0.11.1
- **Compiler/Toolchain**: GCC 7

### Other Notes/Information

[[Write whatever you feel is relevant]]

**Comment by vector-of-bool** [comment]
Interesting... I was seeing a problem a while ago when a HUGE amount of data was written to the logs. If you run the build from the command line, how many lines of output do you see?

I believe I also have a pending fix for some output errors in the 1.0.0 release.

**Comment by josesimoes** [comment]
With the command line I can build without any issues.
As for the lines, they are probably in the thousands....

If that's of interest all this worked in v0.10.X

**Comment by vector-of-bool** [comment]
I think there is an issue in the VSCode OutputChannel when you send huge amounts of data at once. 0.10.x had some workarounds that were removed in 0.11.0 because I thought they weren't required anymore. Seems I was wrong.

**Comment by josesimoes** [comment]
Not sure if this helps, but just got this on the output:

`[cms-client] Unexpected stderr/stdout data from CMake Server process: CMake Error: Internal Error with \\?\pipe\e:\GitHub\nf-interpreter\.vscode\.cmserver-pipe: EADDRINUSE`
